[package]
name = "p3-commit"
version = "0.1.2-succinct"
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
test-utils = ["dep:p3-dft"]

[dependencies]
<<<<<<< HEAD
p3-challenger = { path = "../challenger" }
p3-field = { path = "../field" }
p3-matrix = { path = "../matrix" }
p3-util = { path = "../util" }
=======
p3-challenger = "0.1.2-succinct" 
p3-field = "0.1.2-succinct" 
p3-matrix = "0.1.2-succinct" 
p3-util =  "0.1.2-succinct" 
>>>>>>> 5d76b97 (publishing 0.1.2-succinct)

itertools = "0.12.0"
serde = { version = "1.0", default-features = false }

# for testing
<<<<<<< HEAD
p3-dft = { path = "../dft", optional = true }

[dev-dependencies]
p3-baby-bear = { path = "../baby-bear" }
p3-dft = { path = "../dft" }
rand = "0.8.5"
=======
p3-dft = { version = "0.1.2-succinct", optional = true }

>>>>>>> 5d76b97 (publishing 0.1.2-succinct)
