[package]
name = "p3-air"
version = "0.1.2-succinct"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
<<<<<<< HEAD
p3-field = { path = "../field" }
p3-matrix = { path = "../matrix" }

[dev-dependencies]
p3-matrix = { path = "../matrix" }
=======
p3-field = "0.1.2-succinct" 
p3-matrix = "0.1.2-succinct" 

>>>>>>> 5d76b97 (publishing 0.1.2-succinct)
