[package]
name = "p3-blake3"
version = "0.1.2-succinct"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
<<<<<<< HEAD
p3-symmetric = { path = "../symmetric" }
=======
p3-symmetric = "0.1.2-succinct" 
>>>>>>> 5d76b97 (publishing 0.1.2-succinct)
blake3 = "1.5"

[features]
neon = ["blake3/neon"]
parallel = ["blake3/rayon"]
