[package]
name = "p3-interpolation"
version = "0.1.2-succinct"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
p3-field = "0.1.2-succinct" 
p3-matrix = "0.1.2-succinct" 
p3-util =  "0.1.2-succinct" 

