[package]
name = "p3-poseidon"
version = "0.1.2-succinct"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
p3-field = "0.1.2-succinct" 
p3-mds = "0.1.2-succinct"
p3-symmetric = "0.1.2-succinct" 
rand = "0.8.5"

[[bench]]
name = "poseidon"
harness = false
