[package]
name = "p3-dft"
version = "0.1.2-succinct"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
<<<<<<< HEAD
p3-field = { path = "../field" }
p3-matrix = { path = "../matrix" }
p3-maybe-rayon = { path = "../maybe-rayon" }
p3-util = { path = "../util" }
tracing = "0.1.37"

[dev-dependencies]
p3-baby-bear = { path = "../baby-bear" }
p3-goldilocks = { path = "../goldilocks" }
p3-mersenne-31 = { path = "../mersenne-31" }
criterion = "0.5.1"
rand = "0.8.5"

=======
p3-field = "0.1.2-succinct" 
p3-matrix = "0.1.2-succinct" 
p3-maybe-rayon = "0.1.2-succinct" 
p3-util =  "0.1.2-succinct" 
tracing = "0.1.37"

>>>>>>> 5d76b97 (publishing 0.1.2-succinct)
[[bench]]
name = "fft"
harness = false
