[package]
name = "p3-uni-stark"
version = "0.1.2-succinct"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
<<<<<<< HEAD
p3-air = { path = "../air" }
p3-field = { path = "../field" }
p3-challenger = { path = "../challenger" }
p3-commit = { path = "../commit" }
p3-dft = { path = "../dft" }
p3-matrix = { path = "../matrix" }
p3-maybe-rayon = { path = "../maybe-rayon" }
p3-util = { path = "../util" }
=======
p3-util =  "0.1.2-succinct" 
p3-field = "0.1.2-succinct" 
p3-challenger = "0.1.2-succinct" 
p3-commit = "0.1.2-succinct"
p3-dft = "0.1.2-succinct"
p3-matrix = "0.1.2-succinct" 
p3-maybe-rayon = "0.1.2-succinct" 
p3-air = "0.1.2-succinct"
>>>>>>> 5d76b97 (publishing 0.1.2-succinct)
itertools = "0.12.0"
tracing = "0.1.37"
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }

<<<<<<< HEAD
[dev-dependencies]
p3-baby-bear = { path = "../baby-bear" }
p3-commit = { path = "../commit", features = ["test-utils"] }
p3-circle = { path = "../circle" }
p3-fri = { path = "../fri" }
p3-keccak = { path = "../keccak" }
p3-mds = { path = "../mds" }
p3-merkle-tree = { path = "../merkle-tree" }
p3-goldilocks = { path = "../goldilocks" }
p3-mersenne-31 = { path = "../mersenne-31" }
p3-poseidon2 = { path = "../poseidon2" }
p3-symmetric = { path = "../symmetric" }
rand = "0.8.5"
=======
>>>>>>> 5d76b97 (publishing 0.1.2-succinct)
tracing-subscriber = { version = "0.3.17", features = ["std", "env-filter"] }
tracing-forest = { version = "0.1.6", features = ["ansi", "smallvec"] }
postcard = { version = "1.0.0", default-features = false, features = ["alloc"] }
