[package]
name = "p3-poseidon2"
version = "0.1.2-succinct"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
gcd = "2.3.0"
<<<<<<< HEAD
p3-field = { path = "../field" }
p3-symmetric = { path = "../symmetric" }
p3-mds = { path = "../mds" }
rand = { version = "0.8.5", features = ["min_const_gen"] }

[dev-dependencies]
p3-mersenne-31 = { path = "../mersenne-31" }
p3-baby-bear = { path = "../baby-bear" }
p3-koala-bear = { path = "../koala-bear" }
p3-bn254-fr = { path = "../bn254-fr" }
p3-goldilocks = { path = "../goldilocks" }
criterion = "0.5.1"

=======
p3-field = "0.1.2-succinct" 
p3-symmetric = "0.1.2-succinct" 
p3-mds = "0.1.2-succinct"
rand = { version = "0.8.5", features = ["min_const_gen"] }

>>>>>>> 5d76b97 (publishing 0.1.2-succinct)
[[bench]]
name = "poseidon2"
harness = false
