[package]
name = "p3-goldilocks"
version = "0.1.2-succinct"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
<<<<<<< HEAD
p3-field = { path = "../field" }
p3-dft = { path = "../dft" }
p3-mds = { path = "../mds" }
p3-symmetric = { path = "../symmetric" }
p3-util = { path = "../util" }
p3-poseidon2 = { path = "../poseidon2" }
=======
p3-field = "0.1.2-succinct" 
p3-dft = "0.1.2-succinct"
p3-mds = "0.1.2-succinct"
p3-symmetric = "0.1.2-succinct" 
p3-util =  "0.1.2-succinct" 
p3-poseidon2 = "0.1.2-succinct"
>>>>>>> 5d76b97 (publishing 0.1.2-succinct)
num-bigint = { version = "0.4.3", default-features = false }
rand = "0.8.5"
serde = { version = "1.0", default-features = false, features = ["derive"] }

<<<<<<< HEAD
[dev-dependencies]
p3-field-testing = { path = "../field-testing" }
rand = { version = "0.8.5", features = ["min_const_gen"] }
criterion = "0.5.1"

=======
>>>>>>> 5d76b97 (publishing 0.1.2-succinct)
[[bench]]
name = "bench_field"
harness = false

[[bench]]
name = "extension"
harness = false
