[package]
name = "p3-mds"
version = "0.1.2-succinct"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
<<<<<<< HEAD
p3-dft = { path = "../dft" }
p3-field = { path = "../field" }
p3-matrix = { path = "../matrix" }
p3-symmetric = { path = "../symmetric" }
p3-util = { path = "../util" }
rand = { version = "0.8.5", features = ["min_const_gen"] }
itertools = "0.12.0"

[dev-dependencies]
criterion = "0.5.1"
p3-baby-bear = { path = "../baby-bear" }
p3-goldilocks = { path = "../goldilocks" }
p3-mersenne-31 = { path = "../mersenne-31" }

=======
p3-dft = "0.1.2-succinct"
p3-field = "0.1.2-succinct" 
p3-matrix = "0.1.2-succinct" 
p3-symmetric = "0.1.2-succinct" 
p3-util =  "0.1.2-succinct" 
rand = { version = "0.8.5", features = ["min_const_gen"] }
itertools = "0.12.0"

>>>>>>> 5d76b97 (publishing 0.1.2-succinct)
[[bench]]
name = "mds"
harness = false
