[package]
name = "p3-symmetric"
version = "0.1.2-succinct"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
p3-field = "0.1.2-succinct" 
itertools = "0.12.0"
serde = { version = "1.0", default-features = false, features = ["alloc"] }
