[package]
name = "p3-field-testing"
version = "0.1.2-succinct"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
p3-field = "0.1.2-succinct" 
rand = { version = "0.8.5", features = ["min_const_gen"] }
criterion = "0.5.1"

